import React, { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import DesignModule from "../components/DesignModule";
import DownloadButton from "../components/DownloadButton";

const Home: NextPage = () => {
  const [imageUrl, setImageUrl] = useState("");
  const [frameColor, setFrameColor] = useState("red");

  const toggleImage = () => {
    setImageUrl(
      imageUrl ===
        "https://poap-templates.s3.us-east-2.amazonaws.com/f3aa5f43-c58e-45da-9a88-dc1c6f37bda6.jpeg"
        ? ""
        : "https://poap-templates.s3.us-east-2.amazonaws.com/f3aa5f43-c58e-45da-9a88-dc1c6f37bda6.jpeg"
    );
  };

  const toggleFrameColor = () => {
    setFrameColor(frameColor === "red" ? "green" : "red");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav style={{ padding: 32, backgroundColor: "lightgrey" }}>
        <DownloadButton />
        <button onClick={() => toggleImage()}>Toggle Image</button>
        <button onClick={() => toggleFrameColor()}>Toggle Frame Color</button>
      </nav>
      <main className={styles.main}>
        <DesignModule
          data={{
            background: { color: "#09edb4" },
            imageUrl,
            frame: { color: frameColor, width: 40 },
          }}
        />
      </main>
    </div>
  );
};

export default Home;
