import type { NextPage } from "next";
import Head from "next/head";
import DesignModule from "../components/DesignModule";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <DesignModule
          data={{
            background: { color: "#09edb4" },
            imageUrl: "https://new.poap.gg/images/wavy.png",
            frame: { color: "#83579e", width: 40 },
          }}
        />
      </main>
    </div>
  );
};

export default Home;
