import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import DesignModule from "../components/DesignModule";
import DownloadButton from "../components/DownloadButton";

const Home: NextPage = () => {
  console.log('Booooom =>>>XXXXXX');
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav style={{ padding: 32, backgroundColor: "lightgrey" }}>
        <DownloadButton />
      </nav>
      <main className={styles.main}>
        <DesignModule
          data={{
            background: { color: "#09edb4" },
            imageUrl: "https://poap-templates.s3.us-east-2.amazonaws.com/f3aa5f43-c58e-45da-9a88-dc1c6f37bda6.jpeg",
            frame: { color: "#83579e", width: 40 },
          }}
        />
      </main>
    </div>
  );
};

export default Home;
